function tipGen() {
  const Tips = [
    "Set clear goals for the day",
    "Prioritize tasks using the Eisenhower Matrix (urgent vs. important)",
    "Use the 80/20 rule (focus on tasks that give the most results)",
    "Plan your day the night before",
    "Time block your schedule",
    "Use a to-do list (digital or paper)",
    "Follow the two-minute rule (if it takes ≤2 min, do it now)",
    "Break big tasks into smaller steps",
    "Avoid multitasking—it reduces efficiency",
    "Use SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound)",

    "Start your day with the hardest task (Eat the Frog method)",
    "Set time limits for tasks",
    "Use a calendar (Google Calendar, Outlook, etc.)",
    "Keep a buffer time between tasks",
    "Plan for distractions and interruptions",
    "Avoid overloading your schedule",
    "Batch similar tasks together",
    "Use the Pomodoro Technique (25 min focus, 5 min break)",
    "Identify your peak productivity hours",
    "Set deadlines, even for tasks without one",

    "Put your phone on Do Not Disturb mode",
    "Disable non-essential notifications",
    "Use website blockers (e.g., Freedom, Cold Turkey)",
    "Keep only necessary tabs open",
    "Use noise-canceling headphones",
    "Work in a clutter-free environment",
    "Set clear boundaries with others",
    "Limit social media during work hours",
    "Schedule time for checking emails",
    "Avoid unnecessary meetings",

    "Use task managers (e.g., Todoist, Trello, Notion)",
    "Automate repetitive tasks",
    "Use speech-to-text for faster note-taking",
    "Keep a 'Someday/Maybe' list for non-urgent tasks",
    "Use habit trackers to build routines",
    "Set up email filters and labels",
    "Keep a focus journal to track distractions",
    "Use AI-powered assistants for quick tasks",
    "Try time-tracking apps (e.g., RescueTime, Clockify)",
    "Maintain a digital declutter routine",

    "Start tasks even if you don’t feel ready",
    "Take short breaks to avoid burnout",
    "Stand up and stretch every hour",
    "Set specific study/work hours",
    "Review your progress weekly",
    "Learn to say NO to unnecessary commitments",
    "Assign specific locations for different tasks",
    "Use a whiteboard for visual planning",
    "Prepare a distraction list—write down thoughts for later",
    "Reward yourself for completing tasks",

    "Use keyboard shortcuts",
    "Learn speed reading for quick research",
    "Use templates for repetitive work",
    "Record meetings and take notes later",
    "Turn off auto-play on social media to avoid distractions",
    "Declutter your workspace weekly",
    "Group errands to minimize time wasted",
    "Limit TV and entertainment consumption",
    "Set a bedtime to maintain consistent sleep patterns",
    "Plan meals in advance to save cooking time",

    "Use waiting time productively (read, listen to audiobooks)",
    "Practice saying ‘I’ll get back to you’ to avoid instant commitments",
    "Set a clear morning routine",
    "Create a night routine to wind down",
    "Use alarms or reminders to stay on track",
    "Delegate tasks whenever possible",
    "Minimize decision fatigue by pre-planning outfits and meals",
    "Turn off email notifications and check at set intervals",
    "Use a priority system (A, B, C) for tasks",
    "Reduce the number of tools/apps you use to avoid overload",

    "Use a timer to keep meetings short",
    "Have an accountability partner",
    "Review past mistakes to improve time use",
    "Schedule relaxation and self-care",
    "Avoid perfectionism—done is better than perfect",
    "Schedule deep work sessions with no distractions",
    "Take advantage of commute time for learning",
    "Develop a habit of quick decision-making",
    "Use focus-enhancing music",
    "Try working in sprints rather than long hours",

    "Check your energy levels and schedule accordingly",
    "Identify and eliminate unproductive habits",
    "Avoid unnecessary time spent on emails",
    "Keep essential files organized",
    "Create a ‘Do Not Disturb’ work environment",
    "Develop a personal system for prioritization",
    "Track how you spend your time to find inefficiencies",
    "Block out creative thinking time",
    "Set boundaries for work and personal life",
    "Reassess and adjust your methods regularly",
  ];
  document.getElementById("Tip").innerHTML =
    Tips[Math.floor(Math.random() * 90)];
}
